version: "3.9"

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rails:
    build: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "5001:3000"
    volumes:
      - ./rails:/rails
      - gem_data:/usr/local/bundle
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    env_file:
      - ./rails/.env
    tty: true
    stdin_open: true
  sidekiq:
    build: ./rails
    command: bundle exec sidekiq
    volumes:
      - ./rails:/rails
      - gem_data:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    env_file:
      - ./rails/.env
volumes:
  mysql_data:
  gem_data:
  redis_data:
